//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;



[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name="Shipper", Namespace="http://schemas.datacontract.org/2004/07/")]
public partial class Shipper : object, System.Runtime.Serialization.IExtensibleDataObject
{
    
    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
    
    private string CompanyNameField;
    
    private string PhoneField;
    
    private int ShipperIdField;
    
    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
        get
        {
            return this.extensionDataField;
        }
        set
        {
            this.extensionDataField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string CompanyName
    {
        get
        {
            return this.CompanyNameField;
        }
        set
        {
            this.CompanyNameField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string Phone
    {
        get
        {
            return this.PhoneField;
        }
        set
        {
            this.PhoneField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int ShipperId
    {
        get
        {
            return this.ShipperIdField;
        }
        set
        {
            this.ShipperIdField = value;
        }
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IShipperService")]
public interface IShipperService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShipperService/GetShipper", ReplyAction="http://tempuri.org/IShipperService/GetShipperResponse")]
    Shipper GetShipper(int shipperId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShipperService/SaveShipper", ReplyAction="http://tempuri.org/IShipperService/SaveShipperResponse")]
    void SaveShipper(Shipper shipper);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IShipperServiceChannel : IShipperService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ShipperServiceClient : System.ServiceModel.ClientBase<IShipperService>, IShipperService
{
    
    public ShipperServiceClient()
    {
    }
    
    public ShipperServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ShipperServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ShipperServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ShipperServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public Shipper GetShipper(int shipperId)
    {
        return base.Channel.GetShipper(shipperId);
    }
    
    public void SaveShipper(Shipper shipper)
    {
        base.Channel.SaveShipper(shipper);
    }
}
