//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("PubsEntityModel", "FK__titles__pub_id__07020F21", "publishers", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(PubsEntityModel.Publisher), "titles", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PubsEntityModel.Title), true)]

#endregion

namespace PubsEntityModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class PubsEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new PubsEntities object using the connection string found in the 'PubsEntities' section of the application configuration file.
        /// </summary>
        public PubsEntities() : base("name=PubsEntities", "PubsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PubsEntities object.
        /// </summary>
        public PubsEntities(string connectionString) : base(connectionString, "PubsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PubsEntities object.
        /// </summary>
        public PubsEntities(EntityConnection connection) : base(connection, "PubsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Publisher> Publishers
        {
            get
            {
                if ((_Publishers == null))
                {
                    _Publishers = base.CreateObjectSet<Publisher>("Publishers");
                }
                return _Publishers;
            }
        }
        private ObjectSet<Publisher> _Publishers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Title> Titles
        {
            get
            {
                if ((_Titles == null))
                {
                    _Titles = base.CreateObjectSet<Title>("Titles");
                }
                return _Titles;
            }
        }
        private ObjectSet<Title> _Titles;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Publishers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPublishers(Publisher publisher)
        {
            base.AddObject("Publishers", publisher);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Titles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTitles(Title title)
        {
            base.AddObject("Titles", title);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PubsEntityModel", Name="Publisher")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Publisher : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Publisher object.
        /// </summary>
        /// <param name="publisherId">Initial value of the PublisherId property.</param>
        public static Publisher CreatePublisher(global::System.String publisherId)
        {
            Publisher publisher = new Publisher();
            publisher.PublisherId = publisherId;
            return publisher;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PublisherId
        {
            get
            {
                return _PublisherId;
            }
            set
            {
                if (_PublisherId != value)
                {
                    OnPublisherIdChanging(value);
                    ReportPropertyChanging("PublisherId");
                    _PublisherId = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("PublisherId");
                    OnPublisherIdChanged();
                }
            }
        }
        private global::System.String _PublisherId;
        partial void OnPublisherIdChanging(global::System.String value);
        partial void OnPublisherIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PublisherName
        {
            get
            {
                return _PublisherName;
            }
            set
            {
                OnPublisherNameChanging(value);
                ReportPropertyChanging("PublisherName");
                _PublisherName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PublisherName");
                OnPublisherNameChanged();
            }
        }
        private global::System.String _PublisherName;
        partial void OnPublisherNameChanging(global::System.String value);
        partial void OnPublisherNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String State
        {
            get
            {
                return _State;
            }
            set
            {
                OnStateChanging(value);
                ReportPropertyChanging("State");
                _State = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("State");
                OnStateChanged();
            }
        }
        private global::System.String _State;
        partial void OnStateChanging(global::System.String value);
        partial void OnStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Country
        {
            get
            {
                return _Country;
            }
            set
            {
                OnCountryChanging(value);
                ReportPropertyChanging("Country");
                _Country = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Country");
                OnCountryChanged();
            }
        }
        private global::System.String _Country;
        partial void OnCountryChanging(global::System.String value);
        partial void OnCountryChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PubsEntityModel", "FK__titles__pub_id__07020F21", "titles")]
        public EntityCollection<Title> titles
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Title>("PubsEntityModel.FK__titles__pub_id__07020F21", "titles");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Title>("PubsEntityModel.FK__titles__pub_id__07020F21", "titles", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PubsEntityModel", Name="Title")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Title : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Title object.
        /// </summary>
        /// <param name="titleId">Initial value of the TitleId property.</param>
        /// <param name="titleName">Initial value of the TitleName property.</param>
        /// <param name="type">Initial value of the Type property.</param>
        /// <param name="publishedDate">Initial value of the PublishedDate property.</param>
        public static Title CreateTitle(global::System.String titleId, global::System.String titleName, global::System.String type, global::System.DateTime publishedDate)
        {
            Title title = new Title();
            title.TitleId = titleId;
            title.TitleName = titleName;
            title.Type = type;
            title.PublishedDate = publishedDate;
            return title;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TitleId
        {
            get
            {
                return _TitleId;
            }
            set
            {
                if (_TitleId != value)
                {
                    OnTitleIdChanging(value);
                    ReportPropertyChanging("TitleId");
                    _TitleId = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("TitleId");
                    OnTitleIdChanged();
                }
            }
        }
        private global::System.String _TitleId;
        partial void OnTitleIdChanging(global::System.String value);
        partial void OnTitleIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TitleName
        {
            get
            {
                return _TitleName;
            }
            set
            {
                OnTitleNameChanging(value);
                ReportPropertyChanging("TitleName");
                _TitleName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TitleName");
                OnTitleNameChanged();
            }
        }
        private global::System.String _TitleName;
        partial void OnTitleNameChanging(global::System.String value);
        partial void OnTitleNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PublisherId
        {
            get
            {
                return _PublisherId;
            }
            set
            {
                OnPublisherIdChanging(value);
                ReportPropertyChanging("PublisherId");
                _PublisherId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PublisherId");
                OnPublisherIdChanged();
            }
        }
        private global::System.String _PublisherId;
        partial void OnPublisherIdChanging(global::System.String value);
        partial void OnPublisherIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Price
        {
            get
            {
                return _Price;
            }
            set
            {
                OnPriceChanging(value);
                ReportPropertyChanging("Price");
                _Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Price");
                OnPriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _Price;
        partial void OnPriceChanging(Nullable<global::System.Decimal> value);
        partial void OnPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Advance
        {
            get
            {
                return _Advance;
            }
            set
            {
                OnAdvanceChanging(value);
                ReportPropertyChanging("Advance");
                _Advance = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Advance");
                OnAdvanceChanged();
            }
        }
        private Nullable<global::System.Decimal> _Advance;
        partial void OnAdvanceChanging(Nullable<global::System.Decimal> value);
        partial void OnAdvanceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Royalty
        {
            get
            {
                return _Royalty;
            }
            set
            {
                OnRoyaltyChanging(value);
                ReportPropertyChanging("Royalty");
                _Royalty = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Royalty");
                OnRoyaltyChanged();
            }
        }
        private Nullable<global::System.Int32> _Royalty;
        partial void OnRoyaltyChanging(Nullable<global::System.Int32> value);
        partial void OnRoyaltyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> YtdSales
        {
            get
            {
                return _YtdSales;
            }
            set
            {
                OnYtdSalesChanging(value);
                ReportPropertyChanging("YtdSales");
                _YtdSales = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("YtdSales");
                OnYtdSalesChanged();
            }
        }
        private Nullable<global::System.Int32> _YtdSales;
        partial void OnYtdSalesChanging(Nullable<global::System.Int32> value);
        partial void OnYtdSalesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Notes
        {
            get
            {
                return _Notes;
            }
            set
            {
                OnNotesChanging(value);
                ReportPropertyChanging("Notes");
                _Notes = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Notes");
                OnNotesChanged();
            }
        }
        private global::System.String _Notes;
        partial void OnNotesChanging(global::System.String value);
        partial void OnNotesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime PublishedDate
        {
            get
            {
                return _PublishedDate;
            }
            set
            {
                OnPublishedDateChanging(value);
                ReportPropertyChanging("PublishedDate");
                _PublishedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PublishedDate");
                OnPublishedDateChanged();
            }
        }
        private global::System.DateTime _PublishedDate;
        partial void OnPublishedDateChanging(global::System.DateTime value);
        partial void OnPublishedDateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PubsEntityModel", "FK__titles__pub_id__07020F21", "publishers")]
        public Publisher publisher
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Publisher>("PubsEntityModel.FK__titles__pub_id__07020F21", "publishers").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Publisher>("PubsEntityModel.FK__titles__pub_id__07020F21", "publishers").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Publisher> publisherReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Publisher>("PubsEntityModel.FK__titles__pub_id__07020F21", "publishers");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Publisher>("PubsEntityModel.FK__titles__pub_id__07020F21", "publishers", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
