//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.239.
// 
#pragma warning disable 1591

namespace PubsClient.PubsService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AuthorsSoap", Namespace="http://rstarigan.com/")]
    public partial class Authors : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetAuthorTitlesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAuthorOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateAuthorOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Authors() {
            this.Url = global::PubsClient.Properties.Settings.Default.PubsClient_PubsService_Authors;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAuthorTitlesCompletedEventHandler GetAuthorTitlesCompleted;
        
        /// <remarks/>
        public event GetAuthorCompletedEventHandler GetAuthorCompleted;
        
        /// <remarks/>
        public event UpdateAuthorCompletedEventHandler UpdateAuthorCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rstarigan.com/GetAuthorTitles", RequestNamespace="http://rstarigan.com/", ResponseNamespace="http://rstarigan.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetAuthorTitles(string authorId) {
            object[] results = this.Invoke("GetAuthorTitles", new object[] {
                        authorId});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetAuthorTitlesAsync(string authorId) {
            this.GetAuthorTitlesAsync(authorId, null);
        }
        
        /// <remarks/>
        public void GetAuthorTitlesAsync(string authorId, object userState) {
            if ((this.GetAuthorTitlesOperationCompleted == null)) {
                this.GetAuthorTitlesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAuthorTitlesOperationCompleted);
            }
            this.InvokeAsync("GetAuthorTitles", new object[] {
                        authorId}, this.GetAuthorTitlesOperationCompleted, userState);
        }
        
        private void OnGetAuthorTitlesOperationCompleted(object arg) {
            if ((this.GetAuthorTitlesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAuthorTitlesCompleted(this, new GetAuthorTitlesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rstarigan.com/GetAuthor", RequestNamespace="http://rstarigan.com/", ResponseNamespace="http://rstarigan.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Author GetAuthor(string authorId) {
            object[] results = this.Invoke("GetAuthor", new object[] {
                        authorId});
            return ((Author)(results[0]));
        }
        
        /// <remarks/>
        public void GetAuthorAsync(string authorId) {
            this.GetAuthorAsync(authorId, null);
        }
        
        /// <remarks/>
        public void GetAuthorAsync(string authorId, object userState) {
            if ((this.GetAuthorOperationCompleted == null)) {
                this.GetAuthorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAuthorOperationCompleted);
            }
            this.InvokeAsync("GetAuthor", new object[] {
                        authorId}, this.GetAuthorOperationCompleted, userState);
        }
        
        private void OnGetAuthorOperationCompleted(object arg) {
            if ((this.GetAuthorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAuthorCompleted(this, new GetAuthorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rstarigan.com/UpdateAuthor", RequestNamespace="http://rstarigan.com/", ResponseNamespace="http://rstarigan.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateAuthor(Author author) {
            this.Invoke("UpdateAuthor", new object[] {
                        author});
        }
        
        /// <remarks/>
        public void UpdateAuthorAsync(Author author) {
            this.UpdateAuthorAsync(author, null);
        }
        
        /// <remarks/>
        public void UpdateAuthorAsync(Author author, object userState) {
            if ((this.UpdateAuthorOperationCompleted == null)) {
                this.UpdateAuthorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateAuthorOperationCompleted);
            }
            this.InvokeAsync("UpdateAuthor", new object[] {
                        author}, this.UpdateAuthorOperationCompleted, userState);
        }
        
        private void OnUpdateAuthorOperationCompleted(object arg) {
            if ((this.UpdateAuthorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateAuthorCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rstarigan.com/")]
    public partial class Author {
        
        private string authorIDField;
        
        private string lastNameField;
        
        private string firstNameField;
        
        private string phoneField;
        
        private string addressField;
        
        private string cityField;
        
        private string stateField;
        
        private string zipField;
        
        private bool contractField;
        
        /// <remarks/>
        public string AuthorID {
            get {
                return this.authorIDField;
            }
            set {
                this.authorIDField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string Zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
            }
        }
        
        /// <remarks/>
        public bool Contract {
            get {
                return this.contractField;
            }
            set {
                this.contractField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetAuthorTitlesCompletedEventHandler(object sender, GetAuthorTitlesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAuthorTitlesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAuthorTitlesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetAuthorCompletedEventHandler(object sender, GetAuthorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAuthorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAuthorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Author Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Author)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void UpdateAuthorCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591